markdown: kramdown
highlighter: pygments
permalink: /posts/:title.html
excerpt_separator: "<!-- more -->"

github: vivianliyuhuan
author: "智简云"
email: marketing#slipscloud.com
name: "智简云"
url: http://www.slipscloud.com
domain: www.slipscloud.com
all_categories: [
["android", "产品","/posts/android.html"], 
["customer", "案例","/customer.html"]
["program", "帮助","/posts/program.html"],
["web", "联系我们","/posts/web.html"], 
["linux", "注册","/posts/linux.html"],
["about", "关于","/about.html"]
]

paginate: 8
paginate_path: "posts/page:num"
timezone: America/Los_Angeles

collections:
  docs:
    output: true

gems:
 - jekyll-paginate
